{% set version = "1.66.4" %}

package:
  name: tailscaled
  version: {{ version }}

source:
  - url: https://github.com/tailscale/tailscale/archive/refs/tags/v{{ version }}.tar.gz
    sha256: db94df254a263110439aa9d6cf6e1e64a5644b6e6e459ab5298ba6e478a988cf
    folder: release
  # Checkout git repo to obtain version string
  - git_url: https://github.com/tailscale/tailscale
    git_rev: v{{ version }}
    folder: git

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }} >=1.22
    - go-licenses

test:
  requires:
    - m2-grep  # [win]
  commands:
    - tailscaled --version | grep {{ version }}
    - tailscaled --help

about:
  home: https://tailscale.com
  license: BSD-3-Clause
  license_file:
    - release/LICENSE
    - release/library_licenses/
  summary: The easiest, most secure way to use WireGuard and 2FA.
  doc_url: https://tailscale.com/kb/1017/install
  dev_url: https://github.com/tailscale/tailscale

extra:
  recipe-maintainers:
    - borchero
